### ISSUE TITLE
Create Basic Placeholder Start Screen UI look

### ISSUE THREAD

**Issue by JeremyDoss** [Dallas-Makerspace/Malum-Game-Engine#9]
**Sprites [Update fonts for Title and Text Options]**
   - [ ] Title (and/or logo)
   - [ ] Text Options (New Game/Start Game, Continue, Options)
   - [ ] Version Text Note
   - [ ] Main illustration/logo

**Scripts**
   - [ ] Add nodes and options for above sprites to be static for now

**Comment by Code-Hime** [comment]
Initial design is complete. Need to go back and add new fonts and images provided by Conrad
